#!/bin/bash

# Link in services
ln -s /home/pi/Projects/DangleTeam/services/mpu.service /etc/systemd/system
ln -s /home/pi/Projects/DangleTeam/services/dangleredboard.service /etc/systemd/system

# enable & start services
systemctl daemon-reload
systemctl enable mpu.service
systemctl start mpu.service
systemctl enable dangleredboard.service
systemctl start dangleredboard.service

# View logs
journalctl -b0 --unit=mpu.service,dangleredboard.service
