#!/bin/bash

# Link in services
ln -s /home/pi/project/DangleTeam/services/mpu.service /etc/systemd/system
ln -s /home/pi/project/DangleTeam/services/dangleredboard.service /etc/systemd/system
ln -s /home/pi/project/DangleTeam/services/approxeng.service /etc/systemd/system
#ln -s /home/pi/project/DangleTeam/services/menu.service /etc/systemd/system

# enable & start services
systemctl daemon-reload
systemctl enable mpu.service
systemctl start mpu.service
systemctl enable dangleredboard.service
systemctl start dangleredboard.service
systemctl enable approxeng.service
systemctl start approxeng.service
#systemctl enable menu.service
#systemctl start menu.service

# View logs
journalctl -b0 --unit=mpu.service --unit=dangleredboard.service --unit=approxeng.service --unit=menu.service
